version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    commit-message:
      prefix: ci
      include: scope

  # Maintain dependencies for Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: build
      include: scope
    ignore:
      - dependency-name: "*"
        update-types: [
            "version-update:semver-patch",
          ]
