[package]
name = "nj-example-hash"
version = "0.0.0"
authors = ["fluvio.io"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]


[dependencies]
node-bindgen = { path = "../.." }


[build-dependencies]
node-bindgen = { path = "../../", default-features = false, features = ["build"] }
