[package]
name = "nj-example-tuple"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
node-bindgen = { version = "4.3.0", path = "../.." }

[build-dependencies]
node-bindgen = { version = "4.3.0", path = "../../", features = ["build"] }
