[package]
name = "nj-example-async-cb"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.8"
node-bindgen = { path = "../.."}
fluvio-future = { version = "0.2.0",features=["timer"]}

[build-dependencies]
node-bindgen = { path = "../../", features = ["build"] }