[package]
name = "nj-example-function"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2021"


[lib]
crate-type = ["cdylib"]


[dependencies]
node-bindgen = { path = "../.." }

[build-dependencies]
node-bindgen = { path = "../../", default-features=false, features = ["build"] }