[package]
name = "nj-sys"
version = "3.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
edition = "2021"
description = "low level binding to Node N-API"
repository = "https://github.com/infinyon/node-bindgen"
readme = "README.md"
license = "Apache-2.0"
