[package]
name = "nj-example-uuid"
version = "0.0.0"
authors = ["fluvio.io"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
uuid = { workspace = true }
node-bindgen = { workspace = true}

[build-dependencies]
node-bindgen = {workspace = true, features = ["build"] }
