[package]
name = "nj-example-json"
version = "0.1.0"
authors = ["fluvio.io"]
edition = "2018"


[lib]
crate-type = ["cdylib"]


[dependencies]
node-bindgen = { path = "../.." }
serde_json = "1.0"


[build-dependencies]
node-bindgen = { path = "../../", features = ["build"] }
